1.1. Теоретический материал – Библиотека NumPy NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python. 
Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:  pip install numpy 
Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:     import numpy as np 
Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа. 
Наиболее важные атрибуты объектов ndarray: 
##ndarray.ndim - число измерений (чаще их называют "оси") массива. ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim. ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape. ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные. ndarray.itemsize - размер каждого элемента массива в байтах. ndarray.data - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов. Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html  
 


In [10]:
#1.3.1

import numpy as np

a = np.zeros((8,8), dtype = int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#1.3.2

import numpy as np

a = np.arange(25).reshape(5,5)
for i in range(4):
    a[[i + 1, 0]] = a[[0, i]]
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [21]:
#1.3.3

import numpy as np

a = np.random.random((3, 3, 3))
print(a)

[[[0.73059775 0.89587322 0.02483744]
  [0.00508023 0.12620962 0.0420245 ]
  [0.1459605  0.24805901 0.72376392]]

 [[0.42532352 0.01869471 0.173428  ]
  [0.91788454 0.67315505 0.69552462]
  [0.32987949 0.372102   0.0933633 ]]

 [[0.04173999 0.49677505 0.1354237 ]
  [0.27280974 0.08066794 0.18040155]
  [0.2943898  0.00766636 0.958993  ]]]


In [1]:
#1.3.4

import numpy as np

z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
#1.3.5

import numpy as np

array = np.array([2, 6, 31, 7, 12, 79])
print(np.sort(array)[::-1])

[79 31 12  7  6  2]


In [3]:
#1.3.6

import numpy as np

matrix = np.arange(9).reshape(3, 3)
print("Форма: \n", matrix)
print("Размер: ", matrix.shape)

Форма: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Размер:  (3, 3)


In [4]:
#2.3.1

import pandas as pd
import numpy as np

s1 = pd.Series((0, 0, 0))
s2 = pd.Series((4, 7, 1))

square = np.square(s1 - s2)
sum_square = np.sum(square)
distance = np.sqrt(sum_square)

print(distance)

8.12403840463596


In [14]:
#2.3.2

import pandas as pd

dataframe = pd.read_csv('https://pythonru.com/downloads/pandas_tutorial_read.csv')
print(dataframe)

     2018-01-01 00:01:01;read;country_7;2458151261;SEO;North America
0     2018-01-01 00:03:20;read;country_7;2458151262;...             
1     2018-01-01 00:04:01;read;country_7;2458151263;...             
2     2018-01-01 00:04:02;read;country_7;2458151264;...             
3     2018-01-01 00:05:03;read;country_8;2458151265;...             
4     2018-01-01 00:05:42;read;country_6;2458151266;...             
...                                                 ...             
1789  2018-01-01 23:57:14;read;country_2;2458153051;...             
1790  2018-01-01 23:58:33;read;country_8;2458153052;...             
1791  2018-01-01 23:59:36;read;country_6;2458153053;...             
1792  2018-01-01 23:59:36;read;country_7;2458153054;...             
1793  2018-01-01 23:59:38;read;country_5;2458153055;...             

[1794 rows x 1 columns]


In [17]:
#2.3.3 

import pandas as pd

dataframe = pd.read_csv('https://pythonru.com/downloads/pandas_tutorial_read.csv', delimiter=';', names=['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'])  
print('Head:\n', dataframe.head(2))
print('Tail:\n', dataframe.tail(3))
print('Shape:\n', dataframe.shape)
print('Describe:\n', dataframe.describe())

print('Iloc:\n', dataframe.iloc[1:4])
print('Source with "SEO"\n', dataframe[dataframe['source'] == 'SEO'])

Head:
            my_datetime event    country     user_id source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261    SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262    SEO  South America
Tail:
               my_datetime event    country     user_id   source   topic
1792  2018-01-01 23:59:36  read  country_6  2458153053   Reddit    Asia
1793  2018-01-01 23:59:36  read  country_7  2458153054  AdWords  Europe
1794  2018-01-01 23:59:38  read  country_5  2458153055   Reddit    Asia
Shape:
 (1795, 6)
Describe:
             user_id
count  1.795000e+03
mean   2.458152e+09
std    5.183162e+02
min    2.458151e+09
25%    2.458152e+09
50%    2.458152e+09
75%    2.458153e+09
max    2.458153e+09
Iloc:
            my_datetime event    country     user_id   source          topic
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  co

In [21]:
#3.3.2

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
print(dataframe)

scaler = MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
print(dataframe)

dataframe['sepal_width_cm'] = (dataframe['sepal_width_cm'] - dataframe['sepal_width_cm'].mean()) \
                              /dataframe['sepal_width_cm'].std()


print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 