In [3]:
#1

import numpy as np


class OurNeuralNetwork:

    def __init__(self):
        weights = np.array([0.1, 0.1, 0.1])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)

    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1

def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)


network = OurNeuralNetwork()
x = np.array([1, 2, 3])
print(network.feedforward(x))

0.5482733885555816


In [15]:
#2

import numpy as np

class OurNeuralNetwork:

    def __init__(self):
        weights = np.array([0, 1])
        offset = 15
        self.h1 = Neuron(weights, offset)
        self.h2 = Neuron(weights, offset)
        self.o1 = Neuron(weights, offset)
        self.o2 = Neuron(weights, offset)
    def feedforward(self, x):
        out_h1 = self. h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.feedforward(np.array([out_h1, out_h2]))
        return out_o1, out_o2

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, offset):
        self.weights = weights
        self.offset = offset
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.offset
        return sigmoid(total)

network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(0.9999998874648361, 0.9999998874648361)


In [16]:
#3

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return tanh(x)

def ReLU(x):
    return max(0, x)

import numpy as np

class TanhNeuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return tanh(total)

class TanhOurNeuralNetwork:

    def __init__(self):
        weights = np.array([0.2, 0.2, 0.2])
        bias = 0

        self.h1 = TanhNeuron(weights, bias)
        self.h2 = TanhNeuron(weights, bias)
        self.h3 = TanhNeuron(weights, bias)
        self.o1 = TanhNeuron(weights, bias)

    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1

class ReLUNeutron:
     def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
     def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return ReLU(total)

class ReLuOurNeuralNetwork:

    def __init__(self):
        weights = np.array([0.2, 0.2, 0.2])
        bias = 0

        self.h1 = ReLUNeutron(weights, bias)
        self.h2 = ReLUNeutron(weights, bias)
        self.h3 = ReLUNeutron(weights, bias)
        self.o1 = ReLUNeutron(weights, bias)

    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1

network = ReLuOurNeuralNetwork()
x = np.array([1, 2, 3])
print(network.feedforward(x))

0.7200000000000002


In [17]:
#4

from sklearn.datasets import load_digits, load_boston, load_iris
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
digits = load_digits()
iris = load_iris()

X_digits, Y_digits = iris.data, iris.target
print('Dataset Sizes : ', X_digits.shape, Y_digits.shape)
boston = load_boston()
X_boston, Y_boston = boston.data, boston.target

X_train, X_test, Y_train, Y_test = train_test_split(X_digits, Y_digits, train_size=0.80, test_size = 0.20, stratify=Y_digits, random_state = 123)
mlp_classifier = MLPClassifier(random_state=123)
mlp_classifier.fit(X_train, Y_train)
Y_preds = mlp_classifier.predict(X_test)
print(Y_preds[:15])
print(Y_test[:15])
print('Test Accuracy : %.3f'%mlp_classifier.score(X_test, Y_test))
print('Training Accuracy : %.3f'%mlp_classifier.score(X_train, Y_train))

from sklearn.neural_network import MLPRegressor
import pandas as pd

url = 'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'
dataset = pd.read_csv(url)

X_train, X_test, Y_train, Y_test = train_test_split(dataset.iloc[:, :].values, dataset.iloc[:, :].values,
                                                    train_size=0.80, test_size=0.20, random_state=123)
mlp_regressor = MLPRegressor(random_state=123)
mlp_regressor.fit(X_train, Y_train)
Y_preds = mlp_regressor.predict(X_test)
print(Y_preds[:10])
print(Y_test[:10])
print('Test R*2 Score : %.3f' % mlp_regressor.score(X_test, Y_test))
print('Training R°2 Score : %.3f' % mlp_regressor.score(X_train, Y_train))

Dataset Sizes :  (150, 4) (150,)
[1 0 2 2 0 0 2 2 2 0 0 1 2 1 2]
[1 0 2 2 0 0 2 1 2 0 0 1 2 1 2]
Test Accuracy : 0.933
Training Accuracy : 0.983


C:\Users\approxii\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing datase

[[-7.06623286e-01  5.50073550e+04]
 [-1.42685160e+00  1.23132754e+05]
 [-7.62282224e-01  5.72266289e+04]
 [-1.40256041e+00  1.18178549e+05]
 [-8.78237279e-01  6.51099626e+04]
 [-1.32219779e+00  1.13800168e+05]]
[[3.20000e+00 5.44450e+04]
 [1.05000e+01 1.21872e+05]
 [2.90000e+00 5.66420e+04]
 [9.50000e+00 1.16969e+05]
 [3.20000e+00 6.44450e+04]
 [9.60000e+00 1.12635e+05]]
Test R*2 Score : -2.070
Training R°2 Score : -2.363
